FROM ubuntu:xenial

RUN apt-get update && \
    apt-get upgrade -y && \
    apt install htop nano curl git unzip nfs-common net-tools vim redis-tools telnet iputils-ping mysql-client \
                gettext \
                locales \
                s3fs \
                imagemagick \
                git\
                zip \
                -y
